[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.89.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.88.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/glossary/git/#git-ref"
  to = "/glossary/git/#git-object-id-gitoid"

[[redirects]]
  from = "/glossary/git/#git-ref"
  to = "/glossary/git/#git-object-id-gitoid"

[[redirects]]
  from = "https://gitbom.dev/*"
  to = "https://omnibor.io/:splat"
  status = 301
  force = true
  